# Generated by Django 3.1.6 on 2021-04-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_is_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '博客管理', 'verbose_name_plural': '博客管理'},
        ),
    ]
