# Generated by Django 3.1.6 on 2021-02-08 06:55

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[user.models.StudentIdValidator], verbose_name='学号'),
        ),
    ]
