# Generated by Django 3.1.6 on 2021-02-08 07:00

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210208_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[user.models.StudentIdValidator()], verbose_name='学号'),
        ),
    ]
