# Generated by Django 3.1.6 on 2021-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210211_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='学号'),
        ),
    ]
