# Generated by Django 3.1.6 on 2021-03-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='disabled',
        ),
    ]
