# Generated by Django 3.1.6 on 2021-04-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论管理', 'verbose_name_plural': '评论管理'},
        ),
    ]
