# Generated by Django 3.1.6 on 2021-02-18 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='商品名称')),
                ('company', models.CharField(max_length=150, verbose_name='公司名称')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='订单更新日期')),
                ('uinfo', models.TextField(blank=True, verbose_name='备注信息')),
                ('user', models.ManyToManyField(related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('online', '线上支付'), ('offline', '货到付款')], default='online', max_length=20, verbose_name='支付类型')),
                ('status', models.CharField(choices=[('processed', '已处理'), ('unprocessed', '未处理'), ('closed', '已关闭')], default='unprocessed', max_length=20, verbose_name='订单状态')),
                ('shipping_name', models.CharField(blank=True, max_length=150, verbose_name='物流信息')),
                ('shipping_code', models.CharField(blank=True, max_length=150, verbose_name='物流单号')),
                ('ainfo', models.TextField(verbose_name='管理员备注')),
                ('invoice', models.CharField(choices=[('unwanted', '不需要发票'), ('personal', '个人发票'), ('institution', '内蒙古大学')], default='institution', max_length=20, verbose_name='发票信息')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': '订单处理',
                'verbose_name_plural': '订单处理',
            },
        ),
    ]
