# Generated by Django 3.1.6 on 2021-02-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderlogging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlogging',
            name='update_time',
        ),
    ]
