# Generated by Django 3.1.6 on 2021-02-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderlogging_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlogging',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderlogging',
            name='content',
            field=models.CharField(choices=[('create', '创建订单'), ('update', '修改订单'), ('delete', '删除订单')], default='create', max_length=20, verbose_name='操作内容'),
        ),
    ]
