# Generated by Django 3.1.6 on 2021-02-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210219_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kind',
            field=models.CharField(default='其他', max_length=150, verbose_name='商品种类'),
        ),
    ]
