# Generated by Django 3.1.6 on 2021-04-15 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20210415_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagement',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_org', to='order.order'),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='payment1',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折后总价'),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='unit_price1',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折后单价'),
        ),
    ]
